name: Deploy to Server

# main 브랜치에 푸시가 발생했을 때 이 워크플로우를 실행합니다.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # GitHub Actions SSH 방식은 네이버 클라우드 ACG 제한으로 비활성화
    # 대신 웹훅 방식 사용: http://worker.kmtecherp.com/deploy
    if: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 프로젝트 디렉토리로 이동
          cd "/root/WorkerAnalysisGUI-web"
          # 배포 스크립트 실행
          chmod +x deploy.sh
          bash deploy.sh
